"""init

Revision ID: 00dbcfe18ea4
Revises: 
Create Date: 2019-01-17 23:36:57.504048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dbcfe18ea4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=True),
    sa.Column('email', sa.Unicode(length=100), nullable=True),
    sa.Column('password', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_galleries_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_galleries'))
    )
    op.create_table('galleries_collaborators',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], name=op.f('fk_galleries_collaborators_gallery_id_galleries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_galleries_collaborators_user_id_users')),
    sa.UniqueConstraint('user_id', 'gallery_id', name='const_galleries_collaborators')
    )
    op.create_table('galleries_guests',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], name=op.f('fk_galleries_guests_gallery_id_galleries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_galleries_guests_user_id_users')),
    sa.UniqueConstraint('user_id', 'gallery_id', name='const_galleries_guests')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(length=100), nullable=True),
    sa.Column('file_name', sa.Unicode(length=100), nullable=True),
    sa.Column('review_status', sa.SMALLINT(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], name=op.f('fk_photos_gallery_id_galleries')),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_photos_uploader_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_table('photos_likes',
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_photos_likes_photo_id_photos')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photos_likes_user_id_users')),
    sa.UniqueConstraint('photo_id', 'user_id', name='const_photos_likes')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos_likes')
    op.drop_table('photos')
    op.drop_table('galleries_guests')
    op.drop_table('galleries_collaborators')
    op.drop_table('galleries')
    op.drop_table('users')
    # ### end Alembic commands ###
